/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#061b0e",
        "on-primary": "#ffffff",
        "primary-container": "#1b3022",
        "on-primary-container": "#819986",
        "inverse-primary": "#b4cdb8",
        "primary-fixed": "#d0e9d4",
        "primary-fixed-dim": "#b4cdb8",
        "on-primary-fixed": "#0b2013",
        "on-primary-fixed-variant": "#364c3c",

        "secondary": "#4a654f",
        "on-secondary": "#ffffff",
        "secondary-container": "#c9e7cc",
        "on-secondary-container": "#4e6953",
        "secondary-fixed": "#cceacf",
        "secondary-fixed-dim": "#b0ceb4",
        "on-secondary-fixed": "#062010",
        "on-secondary-fixed-variant": "#334d38",

        "tertiary": "#271013",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#3f2427",
        "on-tertiary-container": "#b0898c",
        "tertiary-fixed": "#ffd9dc",
        "tertiary-fixed-dim": "#e7bcbf",
        "on-tertiary-fixed": "#2d1417",
        "on-tertiary-fixed-variant": "#5d3f42",

        "background": "#fbf9f6",
        "on-background": "#1b1c1a",

        "surface": "#fbf9f6",
        "surface-dim": "#dbdad7",
        "surface-bright": "#fbf9f6",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3f0",
        "surface-container": "#efeeeb",
        "surface-container-high": "#e9e8e5",
        "surface-container-highest": "#e3e2e0",
        "on-surface": "#1b1c1a",
        "on-surface-variant": "#434843",
        "inverse-surface": "#30312f",
        "inverse-on-surface": "#f2f1ee",
        "surface-variant": "#e3e2e0",
        "surface-tint": "#4d6453",

        "outline": "#737973",
        "outline-variant": "#c3c8c1",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        heading: ["Montserrat", "sans-serif"],
        body: ["Inter", "sans-serif"],
        "display-lg": ["Montserrat", "sans-serif"],
        "display-lg-mobile": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "headline-sm": ["Montserrat", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "sm": "0.25rem",
        "md": "0.5rem",
        "lg": "0.75rem",
        "xl": "1rem",
        "2xl": "1.5rem",
        "full": "9999px",
      },
      spacing: {
        "base": "8px",
        "xs": "4px",
        "sm": "12px",
        "md": "24px",
        "lg": "48px",
        "xl": "80px",
        "gutter": "24px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "max-width": "1280px",
      },
      boxShadow: {
        'ambient': '0 4px 20px 0 rgba(27, 28, 26, 0.04)',
        'ambient-hover': '0 8px 30px 0 rgba(27, 28, 26, 0.08)',
        'ambient-deep': '0 12px 40px 0 rgba(27, 28, 26, 0.12)',
      }
    },
  },
  plugins: [],
}
